### PR TITLE
add additional required import for projects not using use_frameworks

### PR DESCRIPTION
**Pull request by sam1463**
**Requirements**

- [ ] I have added test coverage for new or changed functionality
- [x] I have followed the repository's [pull request submission guidelines](../blob/master/CONTRIBUTING.md#submitting-pull-requests)
- [ ] I have validated my changes against all supported platform versions

**Related issues**
#13 #22 

**Describe the solution you've provided**
Add an import to the bridging header to allow building without `use_frameworks`
When trying to use this sdk without `use_frameworks` using the solution recommended [here](https://github.com/launchdarkly/react-native-client-sdk/issues/22#issuecomment-542302858), my project still failed to build due to the following error: `use of undeclared type 'RCTConvert'`. It seemed this just needed to be imported in the bridging header.

**Describe alternatives you've considered**
I was not able to find any alternatives that worked for me. I'm not very familiar with swift or objective c, so happy to receive any feedback on better working solutions.

**Additional context**
With the change in this PR, the change to eventsource suggested in the comment I mentioned above, I am able to use this sdk without `use_frameworks` (I did have to add a bridging header as suggested [here](https://stackoverflow.com/a/54586937) and elsewhere)

### CODE REVIEW

**Comment by bwoskow-ld** [comment]
Hi @sam1463,

Thanks for the second PR (in addition to [this one](https://github.com/launchdarkly/ios-eventsource/pull/30)). Similar to my response on that PR, we'll take a look at this change in the upcoming weeks.

In the meantime don't worry about the iOS build failure -- that's a known issue on the target branch and should be unrelated.

Ben

**Comment by sam1463** [comment]
Hi @bwoskow-ld , I have just updated this PR to include a name change in the android directory in order to not collide with react-native (since the old name was `reactlibrary`). Please advise on whether I should remove this or change the name to something else. I just noticed when trying to build for android in my react-native project that I couldn't do so due to that name collision.

**Comment by bwoskow-ld** [comment]
You should remove this change. We're aware of the poorly namespaced Android package (#25) and have already fixed it on our private mirror of the SDK. The issue will get fixed in the next SDK version. There's no need for you to make that change here as well, but thanks for checking in on it.

Out of curiosity, which other dependency do you have which exports `com.reactlibrary` and causes the collision?

**Comment by sam1463** [comment]
Ok I removed those changes. The other library using the same name is react-native-accessibility https://github.com/MaxToyberman/react-native-accessibility

**Comment by bwoskow-ld** [comment]
FYI, [version 2.0.3](https://github.com/launchdarkly/react-native-client-sdk/releases/tag/2.0.3) resolves the issue you found with the `com.reactlibrary` package. It also fixes the iOS build.

**Comment by sam1463** [comment]
@bwoskow-ld Ok, so should I just close this PR then as obsolete?

**Comment by bwoskow-ld** [comment]
Nope - you should keep this PR open. Your [original commit](https://github.com/launchdarkly/react-native-client-sdk/pull/26/commits/2af8b69dd54ecdb0fc72105f229c10ae23f29c72) is net new. I recommend that you merge `master` into your feature branch and that'll clear up your merge conflicts and should also remove your changes to the android subpackages.

**Comment by torchhound** [comment]
Thank you @sam1463 !

**Pull request merged**
